# Generated by Django 4.2 on 2025-08-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomtype_options_roomtype_display_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(choices=[('STUDIO_A', 'Studio A'), ('STUDIO_A_PROMO', 'Studio A Promo'), ('STUDIO_B', 'Studio B'), ('STUDIO_DELUXE', 'Studio Deluxe'), ('FAMILY_NO_BALCONY', 'Family Room w/o Balcony'), ('FAMILY_WITH_BALCONY', 'Family Room w/ Balcony'), ('PENTHOUSE', 'Penthouse'), ('MODULE_HOUSE', 'Module House'), ('KTV', 'KTV Room'), ('LOFT', 'Loft'), ('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('TRIPLE', 'Triple')], max_length=50, unique=True),
        ),
    ]
