# Generated by Django 4.2 on 2025-08-31 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('AUTO', 'Automatic Backup'), ('MANUAL', 'Manual Backup'), ('IMPORT', 'Data Import')], default='AUTO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_data', models.BinaryField()),
                ('booking_count', models.IntegerField(default=0)),
                ('room_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['backup_type', '-created_at'], name='rooms_datab_backup__380b77_idx'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['-created_at'], name='rooms_datab_created_d55375_idx'),
        ),
    ]
