# Generated by Django 4.2.16 on 2025-08-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='roomtype',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(choices=[('LOFT', 'Loft'), ('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('TRIPLE', 'Triple'), ('STUDIO_A', 'Studio A'), ('STUDIO_A_PROMO', 'Studio A Promo'), ('STUDIO_B', 'Studio B'), ('STUDIO_DELUXE', 'Studio Deluxe'), ('FAMILY_NO_BALCONY', 'Family Room w/o Balcony'), ('FAMILY_WITH_BALCONY', 'Family Room w/ Balcony'), ('PENTHOUSE', 'Penthouse'), ('MODULE_HOUSE', 'Module House'), ('KTV', 'KTV Room')], max_length=50, unique=True),
        ),
    ]
