@echo off
echo Starting Hotel Snow PMS...
echo.
echo Checking Python installation...
python --version
echo.
echo Installing/checking dependencies...
python -m pip install -r requirements.txt
echo.
echo Starting server...
python manage.py runserver 127.0.0.1:8000
pause